### ISSUE TITLE
[BUG] no warning for workerless step

### ISSUE THREAD

**Issue by ymubarka** [LLNL/merlin#211]
## 🐛 Bug Report

**Describe the bug**
merlin not reporting when a step isn't assigned to a worker when running in distributed mode. 

**To Reproduce**
Don't assign a step to a worker in distributed mode and check the study directory.

**Expected behavior**
Ideally it would show that one of the steps isn't assigned to a worker. Currently it does not show any errors/warning and it just doesn't run the step.

**Screenshots**
```
    resources:
        workers:
            merge_posthoc_workers:
                args: -l INFO --concurrency 36 --prefetch-multiplier 1 -Ofair
                steps: [merge_posthoc]
                batch:
                  type: slurm


study:
    - name: setup
      description: 
      run:
          cmd: 

    - name: merge_posthoc
      description: Combines the outputs of the previous step
      run:
          cmd: |
          depends: [setup]


```

EDIT: this is only the case when submitting the spec as a slurm job.

**Comment by ben-bay** [comment]
Thank u @ymubarka

**Comment by ben-bay** [comment]
I hate to break this to you, but I am unable to reproduce this bug. I was able to run this locally and distributed (after adding a `description` section).

**Comment by ben-bay** [comment]
This is what I ran:
```
description:
    name: hi
    description: hi

merlin:
    resources:
        workers:
            merge_posthoc_workers:
                args: -l INFO --concurrency 36 --prefetch-multiplier 1 -Ofair
                steps: [merge_posthoc]


study:
    - name: setup
      description:
      run:
          cmd: echo "hi"

    - name: merge_posthoc
      description: Combines the outputs of the previous step
      run:
          cmd: echo "hi2"
          depends: [setup]
```
