### ISSUE TITLE
[FEATURE] Run workers on mutiple machines

### ISSUE THREAD

**Issue by koning** [LLNL/merlin#67]
A request has been made to run the workers for a given yaml spec on different machines.

The implementation will need to specify the hosts required for a given set of steps in the workers section of the spec. This can be accomplished by adding the "machines" keyword to the workers spec.  All the hosts listed in the machines section will need to have access to the OUTPUT_PATH.  Because of this constraint the OUTPUT_PATH must be a full path that can be checked for existence on all hosts listed in the machines keywords. If the machines keyword is not present, then those workers will be started on all hosts where merlin run-workers is executed.

An example is given below:
```
merlin:
  resources:
    task_server: celery
    workers:
      step1workers:
        args: -O fair --prefetch-multiplier 1 -E -l info --concurrency 36
        batch:
          type: local
        steps: step1
        machines: [host1A, hostB]
      step2workers:
        args: -O fair --prefetch-multiplier 1 -E -l info --concurrency 36
        steps: step2
        batch:
          type: local
        machines: [hostC]
```
